name: CI Schedule

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  schedule:
    uses: Geode-solutions/actions/.github/workflows/ci-schedule.yml@master
    with:
      repos: OpenGeode;OpenGeode-IO;OpenGeode-Geosciences;OpenGeode-GeosciencesIO
    secrets: inherit
