name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Geode-solutions/actions/.github/workflows/cpp-deploy.yml@master
    with:
      name: OPENGEODE_INSPECTOR
      repos: ${{ vars.REPOS }}
    secrets: inherit
